name: CI

on:
  push:
    branches:
      - master

# jobs:
#   build:
#     name: Build site
#     runs-on: ubuntu-latest

#     steps:
#     - uses: jorelali/setup-elm@v1
#       with:
#         elm-version: 0.19.1
#     - run: elm make src/Main.elm --optimize --output=elm.js
#     - run: npx terser elm.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | terser --mangle --output=elm.min.js

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Elm
        uses: jorelali/setup-elm@v1
        with:
          elm-version: 0.19.1
      - name: Build
        run: |
          elm make src/Main.elm --optimize --output=elm.js
          npx terser elm.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | terser --mangle --output=elm.min.js
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: .
        env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
